### ISSUE TITLE
CSS Modules

### ISSUE THREAD

**Issue by hankliu62** [hankliu62/hankliu62.github.com#406]
网页样式的一种描述方法，可以保证某个组件的样式，不会影响到其他组件。

CSS Modules 提供各种插件，支持不同的构建工具。本文使用的是 Webpack 的css-loader插件，它在css-loader后面加了一个查询参数modules，表示打开 CSS Modules 功能。

``` js
module: {
  rules: [
    // ...
    {
      test: /\.css$/,
      loader: "css-loader?modules"
    },
  ]
}
```

### 局部作用域

CSS的规则都是全局的，任何一个组件的样式规则，都对整个页面有效。

产生局部作用域的唯一方法，就是使用一个独一无二的class的名字，不会与其他选择器重名。这就是 CSS Modules 的做法。

``` jsx
import React from 'react';
import style from './App.css';

export default () => {
  return (
    <h1 className={style.title}>
      Hello World
    </h1>
  );
};
```

``` css
/* App.css */

.title {
  color: red;
}
```

最终会编译成

``` html
<h1 class="_3zyde4l1yATCOkgn-DBWEL">
  Hello World
</h1>

<style>
  ._3zyde4l1yATCOkgn-DBWEL {
    color: red;
  }
</style>
```

### 全局作用域

CSS Modules 允许使用`:global(.className)`的语法，声明一个全局规则。凡是这样声明的class，都不会被编译成哈希字符串。

CSS Modules 还提供一种显式的局部作用域语法`:local(.className)`，等同于`.className`

### 定制哈希类名

css-loader默认的哈希算法是`[hash:base64]`，这会将.title编译成`._3zyde4l1yATCOkgn-DBWEL`这样的字符串。

webpack.config.js里面可以定制哈希字符串的格式。

``` js
module: {
  loaders: [
    // ...
    {
      test: /\.css$/,
      loader: "style-loader!css-loader?modules&localIdentName=[path][name]---[local]---[hash:base64:5]"
    },
  ]
}
```

### Class 的的组合

``` css
.className {
  background-color: blue;
}

.title {
  composes: className;
  color: red;
}
```

编译成

``` css
._2DHwuiHWMnKTOYG45T0x34 {
  color: red;
}

._10B-buq6_BEOTOl9urIjf8 {
  background-color: blue;
}
```

``` html
<h1 class="_2DHwuiHWMnKTOYG45T0x34 _10B-buq6_BEOTOl9urIjf8">
  Hello World
</h1>
```

### 组合输入其他模块

``` css
/* another.css */
.className {
  background-color: blue;
}
```

``` css
.title {
  composes: className from './another.css';
  color: red;
}
```

### 输入变量

CSS Modules 支持使用变量，不过需要安装 PostCSS 和 postcss-modules-values。

webpack.config.js

``` js
var values = require('postcss-modules-values');

module.exports = {
  entry: __dirname + '/index.js',
  output: {
    publicPath: '/',
    filename: './bundle.js'
  },
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        use: [
          'babel-loader'
        ],
        query: {
          presets: ['es2015', 'stage-0', 'react']
        }
      },
      {
        test: /\.css$/,
        use: [
          'style-loader',
          {
            loader: 'css-loader',
            options: {
              modules: true,
            }
          },
          'postcss-loader'
        ]
      },
    ]
  },
  postcss: [
    values
  ]
};
```

``` css
/* color.css */

@value blue: #0c77f8;
@value red: #ff0000;
@value green: #aaf200;
```

``` css
@value colors: "./colors.css";
@value blue, red, green from colors;

.title {
  color: red;
  background-color: blue;
}
```
