### ISSUE TITLE
清除浮动有哪些方案？

### ISSUE THREAD

**Issue by hankliu62** [hankliu62/hankliu62.github.com#424]
清除浮动主要是为了解决父元素因为子元素浮动引起高度塌陷的问题。

本质上清除浮动的方式有两种，一种是利用clear属性，一种是利用BFC。

### clear属性

clear属性清除浮动又包括空标签法和伪元素法两种具体代码如下：

- 使用空标签清除浮动 在浮动元素的末尾添加一个空标签，并设置 clear: both 属性，即可清除浮动。例如：

``` html
<div class="float-parent">
  <div class="float-left"></div>
  <div class="float-right"></div>
  <div class="clearfix"></div>
</div>
```
``` css
.clearfix {
  clear: both;
}
```

- 使用 :after 伪元素清除浮动

``` html
<div class="float-parent">
  <div class="float-left"></div>
  <div class="float-right"></div>
  <div class="clearfix"></div>
</div>
```

``` css
.float-parent:after {
  content: "";
  display: table;
  clear: both;
}
```

### BFC

BFC清除浮动的方式有多种，我这里就以overflow为例：

``` html
<div class="float-parent" style="overflow: hidden;">
  <div class="float-left"></div>
  <div class="float-right"></div>
</div>
```
