### ISSUE TITLE
伪类和伪元素有什么区别？

### ISSUE THREAD

**Issue by hankliu62** [hankliu62/hankliu62.github.com#425]
伪类表示被选择元素的某种状态或者选择是，常见的伪类有三种，状态类、结构类和表单类。例如:hover就是状态类伪类，:first-child就是结构类伪类，:cheked就是表单类伪类。

``` css
a:hover { color: red; } /* 鼠标悬停在链接上时文字变成红色 */
input:checked + label { background-color: green; } /* 选中表单元素时相邻的标签背景变成绿色 */
```
伪元素用于创建一些不在文档树中的元素，并为其添加样式。伪元素常见的用途有给元素添加小部件、小图标以及清除浮动。 例如：

``` css
.arrow::before {
  content: "";
  display: block;
  width: 0;
  height: 0;
  border-top: 10px solid transparent;
  border-bottom: 10px solid transparent;
  border-right: 10px solid red;
}
```
另外，虽然没有强制规定，但是伪类通常是单冒号，伪元素通常是用双冒号。
