### ISSUE TITLE
你知道哪些实现元素居中的方案？

### ISSUE THREAD

**Issue by hankliu62** [hankliu62/hankliu62.github.com#426]
1. margin: 0 auto;
``` CSS
.element {
  width: 200px;
  margin: 0 auto;
}
```

2. flex居中
``` css
.parent {
  display: flex;
  justify-content: center;
  align-items: center;
}
.element {
  width: 200px;
  height: 100px;
}
```

3. 绝对定位 + transform实现居中：使用position:absolute属性和top、left、right、bottom属性，适用于元素宽度和高度未知的情况。

``` css
.parent {
  position: relative;
}
.element {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
```

4. text-align: center;适用于内联元素或将display属性设置为inline或inline-block的块级元素的子元素的水平居中。内联元素的垂直居中可以将line-height设置和height相等。

除此之外，还有其它很多居中方式，比如绝对定位 + 负margin、table布局居中、栅格布局居中等等。面试中只要了解每种方式的优缺点和适用场景，讲清楚最常用的几种方式就够了。
