### ISSUE TITLE
移动端1px边框问题怎么解决？

### ISSUE THREAD

**Issue by hankliu62** [hankliu62/hankliu62.github.com#430]
由于不同的设备屏幕像素密度的不同，一些边框、线条等细节元素的显示可能会出现“1px问题”，即在某些设备上，本应该显示为1像素的边框或者线条，实际上却被放大成了2像素或者更多像素，导致显示效果不佳。

常见的解决方案：

1. 使用border-image：使用border-image可以将图片作为边框来显示，避免了使用CSS边框样式时的1px问题。

2. 使用box-shadow：使用box-shadow代替边框，然后将边框设为透明，可以避免1px问题。

``` css
.border {
    box-shadow: 0 0 0 1px #ccc;
}
```

3. border + transform：使用transform将边框缩小一半。

``` css
.border {
    border: 1px solid #ccc;
    transform: scaleY(0.5);
}
```

4. 伪元素 + transform：与3类似，不同的是用伪元素来实现。

``` css
.border:before{
    content: "";
    display: block;
    position: absolute;
    left: 0;
    top: 0;
    bottom: 0;
    right: 0;
    border: 1px solid #ccc;
    transform-origin: 0 0;
    transform: scaleY(0.5);
}
```

在父元素上添加一个伪元素，然后给伪元素设置一个边框，并将其缩小为0.5倍。这样就可以实现1px的边框效果了。

5. 使用viewport单位：使用viewport相关的单位（如vw、vh、vmin和vmax）来设置边框或者线条的大小，可以让元素的大小自适应不同的设备像素密度。
