### ISSUE TITLE
对CSS动画有了解吗，CSS实现动画有哪几种方式？

### ISSUE THREAD

**Issue by hankliu62** [hankliu62/hankliu62.github.com#433]
CSS动画主要包括transition动画、transform动画和animation动画。

1. transition动画：主要用来实现过渡效果，包括颜色、透明度、大小、位置，从一个状态向另一个状态过渡。
``` css
.element {
  transition: property duration timing-function delay;
}
```

2. transform动画：用于对元素进行变形和转换，如旋转、缩放、平移和倾斜等。transform可以配合transition一起使用，例如：

``` css
.element {
  transform: rotate(45deg);
  transition: transform duration timing-function delay;
}
```

3. animation动画：使用@keyframes规则定义一组关键帧，描述元素在动画过程中的样式变化。然后通过animation属性将关键帧应用到元素上：

``` css
@keyframes animationName {
  0% { /* 初始样式 */ }
  50% { /* 中间样式 */ }
  100% { /* 结束样式 */ }
}

.element {
  animation: animationName duration timing-function delay iteration-count direction;
}
```

在日常开发中大多数时候制作简单动画使用一些第三方的CSS动画库就足够了，比如Animate.css、Hover.css，但是复杂动画不仅要考虑CSS，还要考虑JS。在Vue和React这样的框架中，都提供了Transition组件来让我们实现动画。

对于复杂动画，除了实现效果之外还要考虑到动画的性能优化，需要使用Chrome工具去调优。

前端动画是一个可以深入研究的话题，后续我也将会出专栏去深入讲解前端动画。
