### ISSUE TITLE
怎么实现换肤？

### ISSUE THREAD

**Issue by hankliu62** [hankliu62/hankliu62.github.com#435]
1. 使用CSS变量，可以定义一个theme-color变量来存储主题色：

``` css
:root {
  --theme-color: #007bff; /* 定义主题色 */
}
```
然后在需要使用主题色的地方使用var()函数来引用这个变量：

```css
.button {
  background-color: var(--theme-color); /* 使用主题色 */
}
```

再通过JS动态更改这个CSS变量的值，从而实现换肤的效果。

2. 使用class切换，通过添加或移除不同的class来改变元素的样式，从而实现换肤。

比如，可以定义多个class来表示不同的主题样式：

``` css
.theme-blue {
  /* 定义蓝色主题样式 */
  background-color: #007bff;
  color: #fff;
}

.theme-red {
  /* 定义红色主题样式 */
  background-color: #dc3545;
  color: #fff;
}
```
然后在需要换肤的元素上添加对应的class：

``` html
<button class="theme-blue">蓝色主题</button>
<button class="theme-red">红色主题</button>
```
最后再通过JS动态添加或移除这些class来改变元素的样式，来实现换肤的效果。
