### ISSUE TITLE
预编译器用的哪个，了解哪些预编译器语法？

### ISSUE THREAD

**Issue by hankliu62** [hankliu62/hankliu62.github.com#436]
以less为例：

1. 嵌套：最常用的预编译器语法，嵌套写法不仅减少了代码量，也使得样式代码更容易阅读维护了。

2. 变量：可以使用“@”符号定义变量，比如颜色、字体大小、边框等等。

举个例子，我们定义了两个变量：

``` less
@primary-color: #007bff;
@font-size: 14px;
```

然后就可以在需要的地方使用：

``` less
h1 {
  color: @primary-color;
  font-size: @font-size;
}
```

3. 函数：less函数用于封装通用的样式，比如封装一个给元素添加圆角的函数：
``` less
.border-radius(@radius) {
  -webkit-border-radius: @radius;
  -moz-border-radius: @radius;
  border-radius: @radius;
}
```
然后在需要用到的地方调用：

``` less
.box {
  .border-radius(5px);
  border: 1px solid #ccc;
}
```

4. mixin：和函数类似，也可以用来封装通用样式，比如居中、清除浮动等。

以居中为例：

``` less
@mixin center-both {
  display: flex;
  justify-content: center;
  align-items: center;
}
```
然后就可以在需要居中的元素样式里使用了：

``` less
.my-element {
  @include center-both;
  width: 200px;
  height: 200px;
}
```
