### ISSUE TITLE
Less使用心得

### ISSUE THREAD

**Issue by hankliu62** [hankliu62/hankliu62.github.com#9]
## 一、循环动画函数
``` less
.keyframes (@name, @frames) {
    @-webkit-keyframes @name { @frames(); }
       @-moz-keyframes @name { @frames(); }
        @-ms-keyframes @name { @frames();}
         @-o-keyframes @name { @frames(); }
            @keyframes @name { @frames(); }
}

@sub-nav-heigth: 41px;

.fadeLoop(@counter) when (@counter < 16 ) {
    @fadeOutUpName: e("fadeOutUp@{counter}");
    @fadeInDownName: e("fadeInDown@{counter}");

    .keyframes(@fadeOutUpName, {
        from { height: @sub-nav-heigth * @counter; }
        to { height: 0;}
    });

    .keyframes(@fadeInDownName, {
        from {height: 0; }
        to { height: @sub-nav-heigth * @counter;}
    });

    .@{fadeOutUpName} {
        animation-name: @fadeOutUpName;
    }

    .@{fadeInDownName} {
        animation-name: @fadeInDownName;
    }

    .fadeLoop(( @counter + 1 ));
}
.fadeLoop(1);

.animated {
    animation-duration: .3s;
    animation-fill-mode: both;
    overflow: hidden;
}
```
